apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - start: "10.0.20.180"
      stop: "10.0.20.200"
  serviceSelector:
    matchExpressions:
      - key: lb.cilium.io/ip-pool
        operator: In
        values: ["apps"]
---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: homelab-bgp-cluster
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: "homelab-instance"
      localASN: 64513
      peers:
        - name: "physical-router"
          peerASN: 64512
          peerAddress: 10.0.20.1
          peerConfigRef:
            name: "homelab-peer-config"

---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: homelab-peer-config
spec:
  timers:
    connectRetrySeconds: 10
    holdTimeSeconds: 90
    keepAliveSeconds: 30
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "bgp"

---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: advertise-service-ips
  labels:
    advertise: "bgp"
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - "LoadBalancerIP"
      selector:
        matchExpressions:
          - key: lb.cilium.io/ip-pool
            operator: In
            values: ["apps"]