apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: home-assistant-cluster
  namespace: home-assistant
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: homeassistant
      owner: homeassistant
      secret:
        name: home-assistant-secrets
  storage:
    size: 10Gi
    storageClass: local-nvme
  affinity:
    enablePodAntiAffinity: true
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - homelab-01
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - homelab-01
                  - homelab-05
  postgresql:
    parameters:
      shared_buffers: 128MB
      work_mem: 16MB
      max_connections: "100"
