apiVersion: v1
kind: Secret
metadata:
    name: bus-display-calendar
    namespace: bus-display
type: Opaque
stringData:
    outlook-calendar-url: ENC[AES256_GCM,data:ZHWJPaJbgHEqurHODujofFxbL7NMpkiha4pTYFakmzcwZa0S6oFHRpa3UKm4QQNrgQ38BAl4NGEwW2/il32Fr4FbVO95fsJ08pB7lyyNBYfR44rQIWHLR1awT5+GYa9g5xdbR4QgBdLdRSsEEZqZ/R+SpCRWdJ09b5Tl8aj7mtw5L+duUCr8gtcjxFypCuLCzryvvfo=,iv:CQlv/LwiNJz7Kv1JT0RIaoDDkwKFMkuNo3u0lXPa+8w=,tag:w8QrwrzQq7QUG0/sERPb8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjJoRVJDZDM3Y09mUzVt
            aVc3YnQ5UXJJMit5N1hPUHlyUmFGTDdpR1FJCnhjbWxQb2VIdXNGZVZQMzlwT2Q5
            MHl1cGxmN09HTXVQeHhlSThyNnpXNTgKLS0tIGtxS3hTWEdCZVlOekxRQWplNWNh
            a2x2YkdFM2V0QUdOWnpwbUo5Y0FPRjQKl1Db1HBg6kPAq57wO6nVU9bMeczctFvY
            +YMXNAjDjeUTsazudc5FEAzJD8wevbx+KQxpijCREJcsRO77SUWPBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T02:38:14Z"
    mac: ENC[AES256_GCM,data:4iBP7/xIMcsJFoIdDh0jRWYRcLxQKvPI70l/9vcDoPJQvU6NikQgVUt738ERCCaO45e04bUfDp3xHEFVfTx7beTLn49+8XOR+NG9YT7nl83/P2Jq2C9Te8iPg1/dYuUXbZcM9dr2gSJzqaD4uL8lBfh0yMuZsNU2Ea1p1TpVajg=,iv:sVoPAFEzQRfm3A2vw69SgwxFY3vrOeoBWyE3oECbkK0=,tag:NOqkkBUgv/LIGQIbNYBPsQ==,type:str]
    version: 3.13.3
