apiVersion: ENC[AES256_GCM,data:15Y=,iv:12vpJjHoRh8woDoLOR3rI0/vCluiVzOi1zYp0r3vElQ=,tag:tYSuNaeT9KMYSs3RIXrjSg==,type:str]
kind: ENC[AES256_GCM,data:iE9UQhVq,iv:2BolUf6v7lpx8FYj2iS8LOkr3LsZBGu7BxBRD/mDWDQ=,tag:dS6/bQ6c42fKP3hZgcTJZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LWdSNvkq6MdTmqz4Mp9EFijxTZ6fthg=,iv:ADkEQ65lvcNMkie3NrVVLkbcYdQg08QKM+FR5zvjv/o=,tag:08E2WiBwQ/hio0p1OeUvTg==,type:str]
    namespace: ENC[AES256_GCM,data:xdR4EL4P/1B58w==,iv:S2aucdydxRTLbmIlXXeNk21B6LrOO3wOzTcJvjj2/tA=,tag:VlxeoOksXXgF2wb/DA5Rsw==,type:str]
stringData:
    0f08d8c5-6f2c-409e-ba80-dc0601e0227e.json: ENC[AES256_GCM,data:tQQyon1f7AgKWt7dxlQkuBBTpx0nDvOOnRjENzMgRNhjqtVmbeVQLMzLFqvoQwC2fE1VM6vEEmJvJ9BD/mEa/3UuJZ/WZGwyIEFJWlfaC4sB/IkKhmn01EjhQ7t2X45y2pKZJaM9iSN+i98lTmFlNr63hremX8naDwz/9jzm+1kQhbbLGCOVlHmvxvKCRc2Tkh7IveG1gNXrh2tdKoGmkGVEitYf2OUVX3SuEE9k1POV9/+zEaeW0tzX,iv:XN5EpaFs/DaNSUzOOXnOWx5cpxY+wyfuyDy6CX3xOxM=,tag:0/79nXW6pmjj/014aulkEw==,type:str]
type: ENC[AES256_GCM,data:F+ZU/sAw,iv:3LrrWSFPHhW7EEzGV07PGzcc9zVT1LXBsffzzpV2aqI=,tag:F3jasOlI2qH9AxO7mZbc6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOEpzS21QVFpUdklPdGZp
            QkVvZURnem9RT29hNFFiWkVUWG9RWnkvdWdBCjdTbkhDckp1bE01Qnp6VGc1eXF5
            eUhLQ3JxcXZ1TGM4cXVvTWViMmVtVFUKLS0tIFRRaUwxVjRJM25aQmNoVzFIQit4
            TE1JUzlRMk9sUFJrOHA5dW1rRVhEZTAKT//m2vqDoDS8DME38j2km59h+iDc8axz
            YfbVVv8Gy3LON2CYjXgN2gQAuK8nr9dLr5ou3JwTKaPDwPdwW19Xqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-22T16:42:37Z"
    mac: ENC[AES256_GCM,data:318VLd9vqf6tpK++xTn2szboe8yi3LcZ3XjSQ+i1D9ZqnUDRjsGvAFwjfHRryYgjfGUqdl58JluIazy8KytJKsppmym+p+ll5xJjJYwk+4iimZc+tins8HZnVrwukvYOcrjdIjpv4fjyu9TbMAJQTNXFZ2u/9QR6Yehppf+rhHU=,iv:RyxEDXvQbChwVPDOlw4sN7dDp69KtJzeWm8p8Bx001o=,tag:dezxEa0qayCxXJcoRCGLLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
