apiVersion: ENC[AES256_GCM,data:xn0=,iv:XjVDZEIREiuzXL05WvbJCbsr0JLhvFkaRkSeCLJeotM=,tag:5CyOefhb/BZQEgy2Mimc0w==,type:str]
kind: ENC[AES256_GCM,data:zlLLnvuN,iv:tYoS0q8I8kLQJ4Js/JKbHDARgtRdKcBANJNnZr5Qr5M=,tag:rV1CLbpNzgqOCXN2FLsQJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1NAliZfpVxC2knEm4ccrIEkpNs+5SFY=,iv:3F6nfITT+8a6Rg/+ca1AjpwHa8dB5y2pZBEQFfVBFJ8=,tag:cZqP4JPMNmYrCMnlZVDeRA==,type:str]
    namespace: ENC[AES256_GCM,data:AldWPYZ/ewymHA==,iv:CtBmNmVba++8U7n4D+1IL4OmVqpKLvn70UHFirhv3HA=,tag:F62LrfUjKlFcWtva0/g45Q==,type:str]
stringData:
    0f08d8c5-6f2c-409e-ba80-dc0601e0227e.json: ENC[AES256_GCM,data:d3WMiTgMIuqDlatjqhoTAEAGhfE8jAnn9NHMF8Gsc87Z+2bjv0oH7lganjlkKxrbRjkyUU5SZVXx9LO1S3wnGfziB+TT2lRM8dNVlQ8sxthCZlsZuBNI+RXFNCUHpqBDrbbg2blYYMA85xwC61pFpSusW6DB8tMwJgNPD+3nSeiJS9fSK3RT/XyCfujIjLKN74impCZyTAWLINGemjCUPRCZQfOasg==,iv:s29kCh+wARwNj+tAtMvcrJ6zHfboNjJlNY7znl1wLN8=,tag:W2gPfTKN2iptSQ62ainQuw==,type:str]
type: ENC[AES256_GCM,data:o/nvzGdk,iv:hhAcLZd7GXNEy8qhWA86h94YT74depWW2SM8kbMyYt0=,tag:F228W9Xx+10cpO7fflATgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbnJvVlI1U1FSMzVreVZE
            UTNHSkdzNlJKWXNtUHZNdVg2Rk9Rc3F1YWd3CmlMSEZHSGw0OVNBbERqOFBIQ1RO
            Q0RRK1ArNG1pVXd4N1pJb0d2SXhjYW8KLS0tIFRLNGZGY2xDRXJOSG55eWwvOXJ0
            cGY0MDRYakZ5aUpoMU9vcGxVN3FPVGcKpfBEeTFQYu4f1F/sl1h98r6QpRrHsdqQ
            tpO1k3cMnaF1dyRjq0/JOpUBhnLdBbmFdqydQ3c1ImgYzHl7fRsbJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-09-22T16:52:42Z"
    mac: ENC[AES256_GCM,data:3drv2R54pVA0jfiJYvhHSTQVApk4pQ6YOI24CZ4TGJvG5XzupAOQQm4RFOHSd7v88BX+Tbn6i0qEVcr/8Ch3cN9z0w3XrBJ+k45h6urqwfKVFFIJkBoV7BCmRC7e7SsZFXPvlVOPI9VNq4eDLPDEcaJTmjtYOshkOfHfIxff5Ko=,iv:3ljIEEyEZB61m01iVnOIeA49GJO3G5JxZtlIoUf1Ako=,tag:9AVqYP4KndiKHSbXKYYzKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
