apiVersion: ENC[AES256_GCM,data:HJ4=,iv:tLqmUD979whKXjm2jPr0CyYwV8q9eTyiKn02n8jz/Po=,tag:BhwmPTTwk57gPeGkWJCIaA==,type:str]
kind: ENC[AES256_GCM,data:TUPUX3Nc,iv:MKZR5dbmo45Hy1arJWctmXSO6kM8MVYhtaw0IfUlqtk=,tag:5vbCvEnTDT5xh0h6DmdL7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zxDfO3lOvPfwCP+gqY0=,iv:iI18C/F4Mt5BZRkkRGaU8cpUIv0ebaX8rd6L7NWtiOI=,tag:voUKAlRErWiQN0T9myZGGQ==,type:str]
    namespace: ENC[AES256_GCM,data:h1OppI5Uh1kBgF0=,iv:AIwcgqmt8idu2tyxP13AvEvcaU405j+dsA9UQF66Is4=,tag:1aUafFiejsA4vltt4Jlvaw==,type:str]
type: ENC[AES256_GCM,data:lBIJpTg0,iv:yCFhGZlIx/NbU3jHzC8FtADTfxFDbAZYkNt1RSbuMsc=,tag:kXsliSz4QiQHOyeHLa4Skg==,type:str]
stringData:
    identity: ENC[AES256_GCM,data:rhWMrZgoZ0w12XkF+w9jQwd0mpHa/JjfbURutzILBjFVpdiNGIQ9UM01VhqlXr2nx3B6AtUdL26HYOj0baDOtF1cyxE5Riqme2DsCJpdEc2OsI2XY1WfqOMXnDsuv6sTb5kbR2nIRD8KWbAo3j/FhNtZJNjy+4QBIqdi3nALRG6R1D0P0bK+XmZoW9+MeTXdrnIo+fywR+v0iyjmqKVzVHOasQVRXRhzVdpMKOV/TgLPxdTvWIM9N16qia8buBZ67W8CNX6bJgFfmHjp8De1keq9hsz6k84pn4tDXcyAHgJkMtZ+y0zvFKlQuQzwrDM9X+rJMQSq6aBo8BpdOvVJErwyUqfa1rG44keSh+VaDFLysiJa4qg3+fRuU0zjVEGAluSNJ+6NuzJrTGoa4j00y9Cp1nn9wORmz0i0WZqb325eecCa1C5eviNQddL2ieqN5CtP++AbbLDpbIeIO5YkvLWdyBcJSiH7b1mB4BVj5Kx9E6XyWAv17Sv6pmh6WYPGjFnaTQaTP+RVYECrpGdcWe6rJTufvpfPwBsunw1ZgoYgNDGTNW7FwAdUd4nqKPQv,iv:TSlnGnHj+F4avt/MfSXnzztvWV82J5PjoyvU74hx3/U=,tag:JfJrm1aRxxY2mGI1Lkuxsg==,type:str]
    identity.pub: ENC[AES256_GCM,data:rb8j3xris9ktaKJvvpFGqY9xC/NPylKRWESTdF9GQYlTgJNk3X4bOVA4MxC/oY4QkNLcK+GgkAzhBw0Ybnhy4bXrVe0ECv5fkDszAVW0KfwP6l47u+Hxlp8kHhIrJ51ONFR0oNRmcpSBxdpua4MPPOQ=,iv:gWIgQhRgcF5tmUlKn00iSYx2IbcBeZ8oLtKbkNUMwQ8=,tag:e76d+EVtj+J7ht1Qg2t+PA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7rUMjB4oBFm3bnqwNU0mKZHLF2isnVP7Lw8LvB3I8FFl04CfzIZckXngLioxldClHN9Pc4Uow5kEC2jt5FIkPuzgabpdVAKuWT5MqSJH3v5d6xdPPCng1kDPWTk=,iv:/MwavvxlUzFQLDwMRHPFiU5SBiUXLzuid7HdMtXVrZA=,tag:IetYnKc2I0CWpY0T8z4k2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aW00WkFwMUJRMUtHVDZU
            M2NLZjdVZGNEaC9ONzlOT0tkKzM0eHJkTlRZCkpyTDZXeVB1VHhENXF0bWdUSEp0
            K0EzN0xOS2ovU1FvamNZQ3FaVTR2dmMKLS0tIDdkWm5rOUZUbENJNHQ2N1V5K0E1
            L3ZIclJQRTVvS3hMYTlzR3lDcVVadVUKEg//ylP+421YIVOaAoxh+utGiGLhqcsM
            i4mKXwbShkU1dDWQdF9k0l0u3JaczXaT5lDLmFtdhsOCqDdyBpSH7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    lastmodified: "2026-10-05T01:17:16Z"
    mac: ENC[AES256_GCM,data:ifppXie/cMH1l2MZOUIMeEeHbakMNoJmln3gabCx//DAwBEvuWRVNXAUbQTi13uGxmK435g21BuI7kI8XKltGl/6KSnkMI+rrLst0/EbM2YjEoC/cMnApDH6u+87hPYZWnT+D4BMDRz0naWkoo/4RI8wZQE9NOaXYFsUyksWcMA=,iv:OP05g+lZXY7paFHqKrWchJQoNrikFwgaZOXvkAAX5As=,tag:MOh4qPJPJbxPIg5L2JdjZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
