apiVersion: v1
kind: Secret
metadata:
    name: immich-oidc-config
    namespace: immich
type: Opaque
stringData:
    immich.json: ENC[AES256_GCM,data:7v4NvXVo661tMOO4PhTtoHqf21bV6l8oz0ZcOmcCZf7Y94AfgAVdKyfdzE24id7gK/Lw2gCfCQs020Zpmlrjq/CSZiBOjW3aRUdMHrjgjAQB+0GIPj4GYbvmJOY7ImhulAJmIltEUjLU1Ku3fY4AAKcVr9Eera5d31AQSZF5lz4NHn9Haev8Mnz0eyUAw1WkO3nMy4ixY3zT6u8eJyyneTnSDgjM5kovqhv9ZGxuOGh1i4EQbcBbq2lZ/TbmVdJ0VXqeEtoAyiCFNXtrXsx6A42RBgxhtlQKC6PyhJcjoNGXjizbn8CWX9MiX6PhkqVcJLc+TOuv81XEfhbbU3CT/43C+aw+NU9JaQr/CCAad5iI9gLIKyd9CNnxj56g1qYNBR8lZlwxd0jHvMCwhFC7O7MJp9ZCkWqLswVmm+OkN6ITZUzVEFDyJYfb7Q268h2iX/ooFXBuqe4WLLqgEDZwyS0515W6m8JiiSAlOAQuBgakXzVCro82gTSdQrtDY4hsFdc50uQIV3FqSpwX5NBtXKZ374iJezgt0xnyhFbwndE7GpiszDk2BR2glp6Mcf4nTOPwTiI/gIcWmolMUqAIW+QiKgRhCBSSSzij2HFsSjrHQ82U6OrBnSwirGe5fWtAIOlErGxxr6/Ijwhaj5mkL7Ly5ggyVB9yBmb9pcIXDKql4VklvOHyc5k3df/i7XLJZhRgmy1Tcu/4xHLcv/105eYD4viqHT+ajzZaqjHZlw1XOl7GWFIA7P7aQs9lCbRR8PDRkMvx/aNZ1YNaJ4z288L305MdmV130hcDGlzWdriIiulEko3JJoYIMs0olunKJ27xFvZmh/XymUn7xsOJJcp5jW2KEXPXcdLpHT4ykCrRO6udo0ZtPzTjMCLZPP50ChG38aqP+kPjrlLIK0Qko1vHaCWrXAHD0jweI5RFMs8berOZD1xaWPvESoVkRWJ5msnf6tMv4NJRTIck5FN1tjGqjoXEneXUe0zrhuZsLtWm9oixo2hiFCXHcwbI5qeD20Gi8XvDviVx2fDDhAlwUEnVPfqJrv40RC24tWYoz6nAxPZMY5ZEjhZ42F/VOQdmOCbqdqj05Q==,iv:pwX/GTpZvMfHYoCCSj8+SC5wU7KYjmkUPat3LoC/08Y=,tag:J+79vAkobZb46V9kFwhZPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWXI2NmpTaExwL0tYcGZX
            TXRzZ2xWa1F6NEVhWG03Z0pqOU51NHRtZXlBCjY4SFdSdWV0ZmM0c3VuNDRKSFNV
            YzVlbGJGOGFiNExsWDl5MGlxN0x6SlUKLS0tIDU5U3RNMHU2d0p6MkRCNys1TEpS
            eVA2TC9YNWhFVko5aEtUTFJRVTh3dW8K7h5zMcvXizkUMwjv0H7zsQg2zU3JZKdR
            ORDdk7sm4oR4DdId/06lAf98B9BEb/v5UmFyad/FzwaacSlkga3E0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T03:45:47Z"
    mac: ENC[AES256_GCM,data:RLop3C4NBWvW3xkWqPHzy24API9mvgVzkEwWcRo1vC1F13ITwiBHTm8f0jyYN9NXmV0gkyYj5V3T9EsFlofjVK3MPs4aKdFE+giZiwhtZFGzgP7Mld2cNA2pJIfTV++2+uFuqdv1nNMOAPcfFLYal23NInqKPO541GpmNihfNdw=,iv:IFhwspT52iGPn01BdJ5PNcXdXHQRH+wI5Wr/LWH6bvU=,tag:TKhJew0TFVQYL3WgLHedNw==,type:str]
    version: 3.13.3
