apiVersion: v1
kind: Secret
metadata:
    name: immich-oidc-config
    namespace: immich
type: Opaque
stringData:
    immich.json: ENC[AES256_GCM,data:66lhvtUL2Bv/Jh5vMEtG1wy5vI8CCtzfV7674fkAjOagUC2Qvcc5zFZngcNKeRpdY3eOekPsf8xn8AlJ05gkbDWY/Zf+T0cpggPlVvJbWc/YlSOBGzepuDk+vodTL3t72YL7vkIEbsPZfy2GuBvj9DidlfK+e2W39wx/5xezjvCXVV+5OlzXGReTEcAfdxYfrJrjhLBd8Twu+nVtiZMbCvT0IaBiRq7tweajh6KO9+clvKQQOKzyDFYroT/cknVZ/eSOAKOGQ6H1aJ4ZkfBaC0+MN6d+DLySwW/7ZJzQbeLGQsjPOW93l6qewbGz1xEYXRpQY9d9PIh5VtpJ72LXTshTSZacdBBYjvkb0yKWlR0UFxLGXbQCe3tB5npWv5sXaXIzYHTUZNU7Ktixj+Rtqa/yssun2YtYECT0QqEc4V54IAnV6CwHbW7XHBURM72J98nJ/HIs2Xcm1jDaX1HW36PHa6uVTGxE9gRyvw9+lheezuJs3OFx/dYqT+kQOtgoScNA3nu8skDL27h8qqc10ar79B9iKmxsYR6sqQ4f2nifiKtxSuNaReL4xgu9NciMY9Ss8sM8W0NNl/GTAjbSqihj0gp6XHzZab8HrUUPUgNrmY5gAnC86F9eCFL8DaHLafE5RyBEtIF1rJ1V6CV8QoklcEJYpp1kePfRbHIaR2OoJaqbvAaXT6eU4CeRDNSeFe+4buK/bO/8sIGn69Pgn4IaT2i74bWPRGv3XVQL2kw4a5Sm1pCBNHC6u6BODyb2alrvdXbt1QPg51/5TJvXLTPxDKSHGnoIvZbXDKKMould0j8uvpH40eupZU8WMJxS0O3CO5k5BHZ+Je1rIrbfEs5j01OJ5Dt+K0U6KEHU5r5fzs3gB4YaGhWHDhXp85A3d4ZcEpxYXG3r+gqEDYWyU7+hrbgye4ppNVCmnk9jzgDtfwI4ZhI/9g6PLyAkplsbuQQJq1NwiW2P7saQ9YZZpD7VQ16HdNdo0ak3p2+L+dAMCC2OzNY1wvtk57s/3iMXXgfyY5L8o1XzO4RjC7M1YXGlv/GsSic5uNPub5fimrXuJ/Q7E18RGlft0+C3Noubppf9o2Po,iv:CwpmrAZYAwmEdQ2OQSC//B4LVYQOokVjITiUHrY1tfw=,tag:5KbNalaS8pr0shkunmeuAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aHdVdS9BYVNKQ1A5a2xT
            Wm0vdXJWdU1zTWZHTEg5U3hxK09hZXgyczFrClBuYVNxUHRGd1VNZzluUkl2RmZq
            eWxpWkhBQlovZVZkRDlRS0FleXVvbzQKLS0tIEZZNWtuOEszd292cU1HQ1NpV0Vm
            LzdrZTQrK01qemFJcEx4aWE0bGdwdTgKW6T8fnFZQiKybAdx+sGFpcyeHDYaa5EL
            mlOUO9RtE21Wyb5lYs8nv0qoMKfyQDUbFJ2nZywj4+cREtW/UGzCsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2vhn663mmw9ancuwm2hfmtfg4xyus9xlvp8rkep4fpvxlqa9gdsms9usl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T03:52:22Z"
    mac: ENC[AES256_GCM,data:BOu++VERpM4lBpzHcD4Xmk9dMOp1qVSCEullxAwV5kBsZKEAlFnBeNyjIASdGqlOyOi6sRN9kIIlqtENtMEhFyN4aw2lYfomiJ8axYhVsIsb2O7K//C1BmuNAZVoQ6qsresArpD35SYBozXMYrH0HRwLqGzbqKgo67rbvssfhHw=,iv:zw1lO8aHgzav9AcMdmP4tQlzs2O2USMgU0pqk/H3N9M=,tag:2eAaaHj7onhbhojsbPt3bw==,type:str]
    version: 3.13.3
