apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-ntfy-token
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: homelab-secrets
    kind: ClusterSecretStore
  target:
    name: alertmanager-ntfy-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homelab-values
        property: NTFY_TOKEN
