stages:
  - sync
  - build
  # - test
  # - validate
  # - plan
  # - apply
  # - configure

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

sync_to_github:
  stage: sync
  image:
    name: alpine/git:latest
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - git remote add github https://oauth2:$GITHUB_TOKEN@github.com/JEFF7712/homelab.git
    - git fetch --unshallow || git fetch --all

    - echo -e "**NOTE - This repository is a mirror.** Active development happens on [GitLab](https://gitlab.com/JEFF7712/homelab).\n\n$(cat README.md)" > README.md

    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "GitLab Runner"
    - 'git commit -am "Automated: Add GitHub Mirror Warning" || echo "No changes to commit"'

    - git push github HEAD:main --force

build_renovate_agent_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.24.0-debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - infrastructure/automation/images/renovate-agent/**/*
        - .gitlab-ci.yml
  variables:
    IMAGE_TAG: "0.0.$CI_PIPELINE_IID"
    IMAGE_NAME: "jeff7712/homelab-renovate-agent"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR"
      --dockerfile "$CI_PROJECT_DIR/infrastructure/automation/images/renovate-agent/Dockerfile"
      --destination "$IMAGE_NAME:$IMAGE_TAG"

build_renovate_dashboard_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.24.0-debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - infrastructure/automation/images/renovate-dashboard/**/*
        - .gitlab-ci.yml
  variables:
    IMAGE_TAG: "0.0.$CI_PIPELINE_IID"
    IMAGE_NAME: "jeff7712/homelab-renovate-dashboard"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKERHUB_USERNAME\",\"password\":\"$DOCKERHUB_TOKEN\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "$CI_PROJECT_DIR/infrastructure/automation/images/renovate-dashboard"
      --dockerfile "$CI_PROJECT_DIR/infrastructure/automation/images/renovate-dashboard/Dockerfile"
      --destination "$IMAGE_NAME:$IMAGE_TAG"

# check-cluster-access:
#   stage: test
#   image:
#     name: bitnami/kubectl:latest
#     entrypoint: [""]
#   script:
#     - kubectl config use-context JEFF7712/homelab:homelab-agent
#     - echo "Testing connection to the cluster..."
#     - kubectl cluster-info
#     - kubectl get nodes -o wide

# scan-cluster:
#   stage: test
#   image:
#     name: aquasec/trivy:latest
#     entrypoint: [""]
#   script:
#     - trivy k8s JEFF7712/homelab:homelab-agent --report summary --include-namespaces default,media,n8n,distrojeff
#   allow_failure: true
