misconfigurations:
  - id: KSV-0014
    paths:
      - infrastructure/immich/db.yaml
  - id: KSV-0014
    paths:
      - infrastructure/media/flaresolverr.yaml
  - id: KSV-0014
    paths:
      - infrastructure/media/lidarr.yaml
  - id: KSV-0014
    paths:
      - infrastructure/media/slskd.yaml
  - id: KSV-0014
    paths:
      - infrastructure/media/subgen.yaml
  - id: KSV-0014
    paths:
      - infrastructure/media/torrent.yaml
  - id: KSV-0053
    paths:
      - infrastructure/gitlab-runner/rbac.yaml
  - id: DS-0002
    paths:
      - infrastructure/automation/images/ci/Dockerfile
  - id: KSV-0014
    paths:
      - infrastructure/nix-cache/attic.yaml
  - id: KSV-0014
    paths:
      - infrastructure/nix-cache/gc-cronjob.yaml
  - id: KSV-0118
    paths:
      - infrastructure/nix-cache/attic.yaml
  - id: KSV-0118
    paths:
      - infrastructure/nix-cache/gc-cronjob.yaml
