apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-auth
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: homelab-secrets
    kind: ClusterSecretStore
  target:
    name: ntfy-auth
    creationPolicy: Owner
  data:
    - secretKey: auth-users
      remoteRef:
        key: homelab-values
        property: NTFY_AUTH_USERS
    - secretKey: auth-tokens
      remoteRef:
        key: homelab-values
        property: NTFY_AUTH_TOKENS
    - secretKey: auth-access
      remoteRef:
        key: homelab-values
        property: NTFY_AUTH_ACCESS
