apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.49.0
    chart: loki
    helm:
      valuesObject:
        deploymentMode: SingleBinary
        extraEnv:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: accesskey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: minio-creds
                key: secretkey
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          storage:
            type: 's3'
            bucketNames:
              chunks: loki-data
              ruler: loki-ruler
              admin: loki-data
            s3:
              endpoint: http://minio.observability.svc:9000
              accessKeyId: ${MINIO_ACCESS_KEY}
              secretAccessKey: ${MINIO_SECRET_KEY}
              s3ForcePathStyle: true
              insecure: true
        minio:
          enabled: false
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - ServerSideApply=true