apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    targetRevision: 5.4.0
    chart: minio
    helm:
      valuesObject:
        mode: standalone
        replicas: 1
        deploymentUpdate:
          type: Recreate
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 50Gi
          accessMode: ReadWriteOnce
        resources:
          requests:
            memory: 512Mi
        existingSecret: "minio-creds"

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
