apiVersion: v1
kind: PersistentVideo
metadata:
  name: video-gen-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi