apiVersion: v1
kind: Namespace
metadata:
  name: apolline
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apolline-tls
  namespace: apolline
spec:
  secretName: apolline-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - apollinestore.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: apolline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apolline-web
  template:
    metadata:
      labels:
        app: apolline-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: web
        image: ghcr.io/jeff7712/apolline:0.0.13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /run
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: apolline-route
  namespace: apolline
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`apollinestore.com`) || Host(`www.apollinestore.com`)
    kind: Rule
    services:
    - name: apolline-svc
      port: 80
  tls:
    secretName: apolline-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: apolline-svc
  namespace: apolline
spec:
  selector:
    app: apolline-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
