apiVersion: v1
kind: Namespace
metadata:
  name: cr-demo
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cr-demo-tls
  namespace: cr-demo
spec:
  secretName: cr-demo-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - demo.rupan.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: cr-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cr-demo-web
  template:
    metadata:
      labels:
        app: cr-demo-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: web
          image: jeff7712/cr-demo@sha256:65aa32d6593b0d1e8284cd0339a2eafc092b779b99e2df98118c72a1e19e3387
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cr-demo-route
  namespace: cr-demo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.rupan.dev`) || Host(`www.demo.rupan.dev`)
      kind: Rule
      services:
        - name: cr-demo-svc
          port: 80
  tls:
    secretName: cr-demo-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cr-demo-svc
  namespace: cr-demo
spec:
  selector:
    app: cr-demo-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
