apiVersion: v1
kind: Namespace
metadata:
  name: darkbit
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: darkbit-tls
  namespace: darkbit
spec:
  secretName: darkbit-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - darkbitapparel.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: darkbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkbit-web
  template:
    metadata:
      labels:
        app: darkbit-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      securityContext:
        fsGroup: 101
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: web
        image: jeff7712/darkbit:0.0.20
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: tmp
          mountPath: /tmp
        - name: run
          mountPath: /run
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: darkbit-route
  namespace: darkbit
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`darkbitapparel.com`) || Host(`www.darkbitapparel.com`)
    kind: Rule
    services:
    - name: darkbit-svc
      port: 80
  tls:
    secretName: darkbit-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: darkbit-svc
  namespace: darkbit
spec:
  selector:
    app: darkbit-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
