apiVersion: v1
kind: Namespace
metadata:
  name: darkbitapparel
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: darkbitapparel-tls
  namespace: darkbitapparel
spec:
  secretName: darkbitapparel-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - darkbitapparel.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: darkbitapparel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darkbitapparel-web
  template:
    metadata:
      labels:
        app: darkbitapparel-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: web
        image: jeff7712/darkbit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: darkbitapparel-route
  namespace: darkbitapparel
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`darkbitapparel.com`) || Host(`www.darkbitapparel.com`)
    kind: Rule
    services:
    - name: darkbitapparel-svc
      port: 80
  tls:
    secretName: darkbitapparel-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: darkbitapparel-svc
  namespace: darkbitapparel
spec:
  selector:
    app: darkbitapparel-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP