apiVersion: v1
kind: Namespace
metadata:
  name: distrojeff
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: distrojeff-tls
  namespace: distrojeff
spec:
  secretName: distrojeff-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - distrojeff.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: distrojeff
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distrojeff-web
  template:
    metadata:
      labels:
        app: distrojeff-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: web
        image: jeff7712/distrojeff-site:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: distrojeff-site-route
  namespace: distrojeff
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`distrojeff.com`) || Host(`www.distrojeff.com`)
    kind: Rule
    services:
    - name: distrojeff-site-svc
      port: 80
  tls:
    secretName: distrojeff-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: distrojeff-site-svc
  namespace: distrojeff
spec:
  selector:
    app: distrojeff-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP