apiVersion: v1
kind: Namespace
metadata:
  name: sf
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sf-tls
  namespace: sf
spec:
  secretName: sf-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sandhufiles.site
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: sf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sf-web
  template:
    metadata:
      labels:
        app: sf-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: web
        image: jeff7712/countdown:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sf-route
  namespace: sf
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`sandhufiles.site`) || Host(`www.sandhufiles.site`)
    kind: Rule
    services:
    - name: sf-svc
      port: 80
  tls:
    secretName: sf-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: sf-svc
  namespace: sf
spec:
  selector:
    app: sf-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP