apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ledfx-data
  namespace: music-assistant
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-cluster
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledfx
  namespace: music-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ledfx
  template:
    metadata:
      labels:
        app: ledfx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: homelab-05
      securityContext:
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ledfx
          image: registry.rupan.dev/upstream/ghcr.io/ledfx/ledfx@sha256:a5ff8549a847d1b2a10595a1137cc4e7352f7d29aafb96eff63cef92634b3036  # yamllint disable-line rule:line-length
          env:
            - name: TZ
              value: America/Chicago
            - name: LEDFX_PORT
              value: "8888"
            - name: PULSECLIENTMODE
              value: "true"
            - name: PULSE_SERVER
              value: unix:/run/user/1001/pulse/native
            - name: PULSE_SOURCE
              value: alsa_output.usb-Generic_USB_SPDIF_Adapter_202110200032-00.analog-stereo.monitor
          ports:
            - containerPort: 8888
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /home/ledfx/ledfx-config
            - name: pulse-socket
              mountPath: /run/user/1001/pulse
          readinessProbe:
            httpGet:
              path: /api/info
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/info
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: ledfx-data
        - name: pulse-socket
          hostPath:
            path: /run/user/1001/pulse
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ledfx
  namespace: music-assistant
spec:
  selector:
    app: ledfx
  ports:
    - name: http
      port: 8888
      targetPort: 8888
