apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - network-policy.yaml
  - secrets.yaml
  - storage.yaml
  - volumes.yaml
  - configs.yaml
  - arr.yaml
  - arr-secret-sync.yaml
  - arr-queue-hygiene.yaml
  - spotify-sync.yaml
  - soularr.yaml
  - download.yaml
  - jellyfin.yaml
  - books.yaml
  - music.yaml
  - frontend.yaml
