apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: metallb
      version: "0.15.3"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  install:
    createNamespace: false
  values:
    controller:
      logLevel: debug
    speaker:
      logLevel: debug
      env:
        - name: METALLB_ML_BIND_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: METALLB_ML_LABELS
          value: "app=metallb,component=speaker"
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true