apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwarden-secrets-manager:
      organizationId: "homelab"
      projectId: "homelab"
      apiUrl: "http://external-secrets-bitwarden-sdk-server.external-secrets.svc:9998"
      auth:
        secretRef:
          name: bw-auth-token
          key: token
          namespace: external-secrets
