apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-media-pvc
  namespace: media
spec:
  template:
    spec:
      containers:
      - name: rsync
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: 
          - apk add --no-cache rsync && rsync -avxP /source/ /destination/
        volumeMounts:
        - name: source-vol
          mountPath: /source
        - name: dest-vol
          mountPath: /destination
      restartPolicy: Never
      volumes:
      - name: source-vol
        persistentVolumeClaim:
          claimName: media-pvc
      - name: dest-vol
        persistentVolumeClaim:
          claimName: media-pvc-hdd
  backoffLimit: 2
