apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: "38.x.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
    service:
      enabled: true
      type: LoadBalancer    
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    securityContext:
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65532
      runAsGroup: 65532