common:
  configStorageClass: longhorn
  configStorage: 2Gi
  mediaClaim: media-pvc-hdd
  timezone: America/Chicago
  uid: "1000"
  gid: "1000"
  permissionImage: busybox@sha256:fd8d9aa63ba2f0982b5304e1ee8d3b90a210bc1ffb5314d980eb6962f1a9715d

workloads:
  sonarr:
    image: lscr.io/linuxserver/sonarr@sha256:0b3f344388bd7bed4f2f770058de795e76447e4a481b83c8d5f8fed489371fde
    port: 8989
    media: true
    fixPermissions: true
    reloader: true
    livenessProbe:
      httpGet:
        path: /ping
        port: 8989
      initialDelaySeconds: 120
      periodSeconds: 20

  radarr:
    image: lscr.io/linuxserver/radarr@sha256:c0a4335d4249b46102f64cf6fa27ffc3bddfd9138fac1e4ddf238afd37f02d1f
    port: 7878
    media: true
    fixPermissions: true
    reloader: true

  lidarr:
    image: ghcr.io/hotio/lidarr@sha256:f8a76d2ff0dac8e449c93c7c0e81b5fb063a3cd926d12420fdb1388818d2fdfe
    port: 8686
    configStorage: 20Gi
    media: true
    fixPermissions: true
    reloader: true
    deploymentLabels: true
    readOnlyRootFilesystem: false
    command:
      - /bin/sh
      - -c
    args:
      - apk add --no-cache ffmpeg && command -v ffprobe >/dev/null 2>&1 && exec /init
    extraEnv:
      - name: lidarrUrl
        value: http://127.0.0.1:8686
      - name: DEEZER_ARL
        valueFrom:
          secretKeyRef:
            name: lidarr-secret
            key: DEEZER_ARL
    extendedConfig: true

  prowlarr:
    image: lscr.io/linuxserver/prowlarr@sha256:2489c6dbaf11e3a6d71aeb2e6980d04193d4af611aa7064a974851222fd41722
    port: 9696
    reloader: true

  bazarr:
    image: lscr.io/linuxserver/bazarr@sha256:4b5e510042bf471c8bafab89cada9774fba2fb25f16ec64235151cacbe847c10
    port: 6767
    media: true
    deploymentLabels: true
