apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moltbot-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi