apiVersion: v1
kind: Namespace
metadata:
  name: temp2-rupan
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: temp2-rupan-tls
  namespace: temp2-rupan
spec:
  secretName: temp2-rupan-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - temp2.rupan.dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: temp2-rupan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temp2-rupan-web
  template:
    metadata:
      labels:
        app: temp2-rupan-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: web
        image: jeff7712/minimalist-chemistry-aesthetic:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: temp2-rupan-route
  namespace: temp2-rupan
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`temp2.rupan.dev`) || Host(`www.temp2.rupan.dev`)
    kind: Rule
    services:
    - name: temp2-rupan-svc
      port: 80
  tls:
    secretName: temp2-rupan-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: temp2-rupan-svc
  namespace: temp2-rupan
spec:
  selector:
    app: temp2-rupan-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP