apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  url: https://metallb.github.io/metallbapiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: metallb
      version: "0.15.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 1h
  targetNamespace: metallb-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace