apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-cert
  namespace: podinfo
spec:
  secretName: podinfo-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: podinfo.local
  dnsNames:
    - podinfo.local
