apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo
  namespace: podinfo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`podinfo.local`)
      kind: Rule
      services:
        - name: podinfo
          port: 9898
  tls: {}