apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
  labels:
    io.cilium/bgp-advertise: "true"
spec:
  blocks:
    - start: "10.0.20.180"
      stop: "10.0.20.190"
  serviceSelector:
    matchLabels:
      io.cilium/bgp-advertise: "true"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisement
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          io.cilium/bgp-advertise: "true"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPNodeConfig
metadata:
  name: controlplane-01-vm
spec:
  bgpInstances:
    - name: "instance-64512"
      localASN: 64512
      peers:
        - name: "opnsense"
          peerAddress: "10.0.20.1"
          peerASN: 64512