apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: legacy-bgp-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: controlplane-01-vm
  virtualRouters:
    - localASN: 64512
      exportPodCIDR: false
      neighbors:
        - peerAddress: "10.0.20.1/32"
          peerASN: 64512
      serviceSelector:
        matchLabels:
          io.cilium/bgp-advertise: "true"