apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: homelab-pool
spec:
  cidrs:
  - cidr: "10.0.20.184/29"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: announce-policy
spec:
  interfaces:
  - ens18
  externalIPs: true
  loadBalancerIPs: true