---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tutor-rupan-tls
  namespace: default
spec:
  secretName: tutor-rupan-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - tutor.rupan.dev
