apiVersion: batch/v1
kind: Job
metadata:
  name: enable-strict-arp
  namespace: kube-system
spec:
  template:
    spec:
      serviceAccountName: kube-proxy
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl get configmap kube-proxy -n kube-system -o yaml | \
          sed -e "s/strictARP: false/strictARP: true/" | \
          kubectl apply -f - -n kube-system
      restartPolicy: OnFailure