[infrastructure:children]
alpine_nodes
talos
bsd_nodes
netbird_gateway

[alpine_nodes]
chromebook ansible_host=192.168.1.70 ansible_user=root

[talos]
controlplane-01-vm ansible_host=10.0.20.101
worker-01-vm ansible_host=10.0.20.104
# worker-01-cli ansible_host=10.0.20.104
# worker-02-cli ansible_host=10.0.20.105
# worker-03-wyse ansible_host=10.0.20.106

[bsd_nodes]
opnsense-router ansible_host=192.168.1.1 ansible_user=admin ansible_connection=local ansible_ssh_common_args='-o ProxyCommand=none'

[talos:vars]
ansible_connection=local

[netbird_gateway]
netbird_lxc ansible_host=192.168.1.5 ansible_user=root
chromebook ansible_host=192.168.1.70 ansible_user=root