apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets
  namespace: automation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: homelab-secrets
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
  data:
    - secretKey: forgejo-approval-token
      remoteRef:
        key: homelab-values
        property: FORGEJO_DASHBOARD_APPROVAL_TOKEN
    - secretKey: forgejo-token
      remoteRef:
        key: homelab-values
        property: FORGEJO_RENOVATE_TOKEN
    - secretKey: ntfy-token
      remoteRef:
        key: homelab-values
        property: NTFY_TOKEN
    - secretKey: dockerhub-username
      remoteRef:
        key: homelab-values
        property: DOCKERHUB_USERNAME
    - secretKey: dockerhub-token
      remoteRef:
        key: homelab-values
        property: DOCKERHUB_TOKEN
    - secretKey: github-token
      remoteRef:
        key: homelab-values
        property: GITHUB_TOKEN
    - secretKey: openai-api-key
      remoteRef:
        key: homelab-values
        property: OPENAI_API_KEY
