apiVersion: v1
kind: Namespace
metadata:
  name: automation
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://gitlab.com/JEFF7712/homelab.git"
    targetRevision: main
    path: infrastructure/automation
  destination:
    server: https://kubernetes.default.svc
    namespace: automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
