apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audiobookshelf
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.christianhuth.de
    chart: audiobookshelf
    targetRevision: 1.6.1
    helm:
      values: |
        image:
          registry: docker.io
          repository: advplyr/audiobookshelf
          tag: "2.32.1"
          pullPolicy: Always

        ingress:
          enabled: true
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          hosts:
            - host: books.rupan.dev
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: books-tls
              hosts:
                - books.rupan.dev

        audiobookshelf:
          library:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi

          config:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 2Gi

          metadata:
            persistence:
              enabled: true
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi

          backup:
            persistence:
              enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: media
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true