apiVersion: v1
kind: Namespace
metadata:
  name: darkbit
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: darkbit-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/JEFF7712/homelab.git'
    targetRevision: main
    path: infrastructure/darkbit-site
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: darkbit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true