apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitlab-backend
spec:
  provider:
    gitlab:
      url: https://gitlab.com
      projectID: "homelab"
      auth:
        SecretRef:
          accessToken:
            name: gitlab-auth
            key: token
            namespace: external-secrets