apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gitlab-backend
spec:
  provider:
    gitlab:
      url: https://gitlab.com
      projectID: "77074161"
      auth:
        SecretRef:
          accessToken:
            name: gitlab-auth
            key: token
            namespace: external-secrets