apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fipet-coin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://gitlab.com/JEFF7712/homelab.git"
    targetRevision: main
    path: infrastructure/fipet
  destination:
    server: "https://kubernetes.default.svc"
    namespace: fipet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
