apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.1
    helm:
      values: |
        persistence:
          defaultClassReplicaCount: 1
          
        defaultSettings:
          replicaAutoBalance: "best-effort"
          
        global:
          cattle:
            psp:
              enabled: false

        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.rupan.dev
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          tls: true
          tlsSecret: longhorn-tls
          
        preUpgradeChecker:
          jobEnabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
