apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: n8n
    targetRevision: 1.16.14 
    helm:
      values: |
        config:
          encryptionKey:
            existingSecret: n8n-secret
            encryptionKeyKey: encryption-key
        persistence:
          enabled: true
          storageClass: longhorn
          size: 10Gi
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          hosts:
            - host: n8n.rupan.dev
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: n8n-tls
              hosts:
                - n8n.rupan.dev
        podSecurityContext:
          fsGroup: 1000
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true