apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nix-cache
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/JEFF7712/homelab.git'
    targetRevision: main
    path: infrastructure/nix-cache
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nix-cache
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
