---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iso-rupan-cert
  namespace: default
spec:
  secretName: iso-rupan-tls
  dnsNames:
    - nix.rupan.dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: nixos-iso-origin
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nixos-iso-origin
subsets:
  - addresses:
      - ip: 192.168.1.70
    ports:
      - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nixos-iso-web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nix.rupan.dev`)
      kind: Rule
      services:
        - name: nixos-iso-origin
          port: 443
          scheme: http
  tls:
    secretName: iso-rupan-tls