apiVersion: v1
kind: Namespace
metadata:
  name: openclaw
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/JEFF7712/homelab.git'
    targetRevision: main
    path: infrastructure/openclaw-hive
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openclaw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true