apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 18.2.0
    helm:
      values: |
        global:
          storageClass: longhorn
        auth:
          existingSecret: postgres-auth
          database: n8n_db
          username: n8n_user
        primary:
          persistence:
            size: 8Gi
          podSecurityContext:
            fsGroup: 1001
          containerSecurityContext:
            runAsUser: 1001
        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true