apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rupan-sites
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/JEFF7712/homelab.git'
    targetRevision: main
    path: infrastructure/rupan-sites
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true