apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v2.5.6
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          env:
            - name: TZ
              value: America/Chicago
            - name: DB_HOSTNAME
              value: immich-postgres
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_PASSWORD
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: DB_DATABASE_NAME
            - name: REDIS_HOSTNAME
              value: immich-redis
            - name: IMMICH_MACHINE_LEARNING_URL
              value: "http://immich-machine-learning:3003"
          volumeMounts:
            - name: library-volume
              mountPath: /usr/src/app/upload
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: library-volume
          persistentVolumeClaim:
            claimName: immich-library-pvc
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
spec:
  selector:
    app: immich-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2283

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-server
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - photos.rupan.dev
      secretName: immich-tls
  rules:
    - host: photos.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: immich-server
                port:
                  number: 80
