apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: "7.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values:
    persistence:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.local
