apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - volume.yaml
  - configmap.yaml
  - externalsecret.yaml
  - dashboard.yaml
  - discord-bot.yaml
  - cronjobs-daily.yaml
  - cronjobs-frequent.yaml
  - cronjobs-weekly.yaml
