apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: media
  labels:
    app: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:2.32.1
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /audiobooks
              subPath: audiobooks
            - name: media-storage
              mountPath: /metadata
              subPath: audiobooks-metadata
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd
        - name: config-storage
          persistentVolumeClaim:
            claimName: audiobookshelf-config
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: media
spec:
  selector:
    app: audiobookshelf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - books.rupan.dev
      secretName: books-tls
  rules:
    - host: books.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: audiobookshelf
                port:
                  number: 80
