# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: aurral-config
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: aurral
#   namespace: media
# spec:
#   replicas: 1
#   strategy:
#     type: Recreate
#   selector:
#     matchLabels:
#       app: aurral
#   template:
#     metadata:
#       labels:
#         app: aurral
#       annotations:
#         reloader.stakater.com/auto: "true"
#     spec:
#       securityContext:
#         fsGroup: 1000
#         fsGroupChangePolicy: "OnRootMismatch"
#       containers:
#         - name: aurral
#           image: ghcr.io/lklynet/aurral:latest
#           imagePullPolicy: IfNotPresent
#           env:
#             - name: PORT
#               value: "3001"
#             - name: TRUST_PROXY
#               value: "true"
#             - name: PUID
#               value: "1000"
#             - name: PGID
#               value: "1000"
#             - name: DOWNLOAD_FOLDER
#               value: "/media/downloads"
#           ports:
#             - containerPort: 3001
#           volumeMounts:
#             - name: config-storage
#               mountPath: /app/backend/data
#             - name: media-storage
#               mountPath: /app/downloads
#               subPath: downloads
#             - name: media-storage
#               mountPath: /media/downloads
#               subPath: downloads
#       volumes:
#         - name: config-storage
#           persistentVolumeClaim:
#             claimName: aurral-config
#         - name: media-storage
#           persistentVolumeClaim:
#             claimName: media-pvc-hdd
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: aurral
#   namespace: media
# spec:
#   selector:
#     app: aurral
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 3001
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: aurral
#   namespace: media
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
# spec:
#   ingressClassName: traefik
#   tls:
#     - hosts:
#         - aurral.rupan.dev
#       secretName: aurral-tls
#   rules:
#     - host: aurral.rupan.dev
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: aurral
#                 port:
#                   number: 80
