apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshelf
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookshelf
  template:
    metadata:
      labels:
        app: bookshelf
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /config"]
          volumeMounts:
            - name: config-storage
              mountPath: /config
      containers:
        - name: bookshelf
          image: ghcr.io/pennydreadful/bookshelf:hardcover
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /data
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd
        - name: config-storage
          persistentVolumeClaim:
            claimName: bookshelf-config
---
apiVersion: v1
kind: Service
metadata:
  name: bookshelf
  namespace: media
spec:
  selector:
    app: bookshelf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8787
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - bookshelf.rupan.dev
      secretName: bookshelf-tls
  rules:
    - host: bookshelf.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookshelf
                port:
                  number: 80
