apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /config /calibre-library /cwa-book-ingest"]
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /calibre-library
              subPath: books/library
            - name: media-storage
              mountPath: /cwa-book-ingest
              subPath: books/ingest
      containers:
        - name: calibre-web
          image: crocodilestick/calibre-web-automated:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /calibre-library
              subPath: books/library
            - name: media-storage
              mountPath: /cwa-book-ingest
              subPath: books/ingest
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd
        - name: config-storage
          persistentVolumeClaim:
            claimName: calibre-web-config
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web
  namespace: media
spec:
  selector:
    app: calibre-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - books.rupan.dev
      secretName: calibre-web-tls
  rules:
    - host: books.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web
                port:
                  number: 80
