apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /config /data"]
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /data
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            - name: JELLYFIN_PublishedServerUrl
              value: "https://jellyfin.rupan.dev"
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /data
            - name: render-device
              mountPath: /dev/dri
          securityContext:
            privileged: true
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd
        - name: config-storage
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: render-device
          hostPath:
            path: /dev/dri
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - jellyfin.rupan.dev
      secretName: jellyfin-tls
  rules:
    - host: jellyfin.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 80