apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
  labels:
    app: lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd

      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /music /downloads /config"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /downloads
              subPath: downloads
            - name: media-storage
              mountPath: /music
              subPath: music

      containers:
        - name: lidarr
          image: ghcr.io/hotio/lidarr:nightly
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            - name: lidarrUrl
              value: "http://127.0.0.1:8686"
            - name: DEEZER_ARL
              value: "ea8d49952bb64817dc618ff4f713303b955f75da8dcc58edc3a2ee28743dd0548cc2790e8fe21b8c637e6317da3d1ae006ff50e15dba89f458d75cc2271e99c30eff659e896dcc14e5b3e50b5317b2a2bf8fdbe17f92ff423c5872600b275996"
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: config-storage
              mountPath: /config
            - name: media-storage
              mountPath: /data

---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  selector:
    app: lidarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8686

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lidarr.rupan.dev
      secretName: lidarr-tls
  rules:
    - host: lidarr.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: 80
