apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - qbittorrent
              topologyKey: "kubernetes.io/hostname"

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: custom-init-scripts
          emptyDir: {}

      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /music /downloads /config"]
          volumeMounts:
            - name: media-storage
              mountPath: /config
              subPath: lidarr-config
            - name: media-storage
              mountPath: /downloads
              subPath: downloads
            - name: media-storage
              mountPath: /music
              subPath: music

        - name: install-extended-scripts
          image: busybox:latest
          securityContext:
            runAsUser: 0
          command:
            - "sh"
            - "-c"
            - |
              wget -O /custom-cont-init.d/scripts_init.bash https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/lidarr/scripts_init.bash
              chmod -R +x /custom-services.d/ 2>/dev/null || true
              chown root:root /custom-cont-init.d/scripts_init.bash
          volumeMounts:
            - name: media-storage
              mountPath: /config
              subPath: lidarr-config
            - name: media-storage
              mountPath: /custom-services.d
              subPath: lidarr-config/custom-services.d

      containers:
        - name: lidarr
          image: lscr.io/linuxserver/lidarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: media-storage
              mountPath: /custom-services.d
              subPath: lidarr-config/custom-services.d
            - name: media-storage
              mountPath: /config
              subPath: lidarr-config
            - name: media-storage
              mountPath: /downloads
              subPath: downloads
            - name: media-storage
              mountPath: /music
              subPath: music

---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  selector:
    app: lidarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8686

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - lidarr.rupan.dev
      secretName: lidarr-tls
  rules:
    - host: lidarr.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lidarr
                port:
                  number: 80