apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi
  volumeName: pvc-625f29b5-1eaf-42e3-9628-55e25efcb7ab