apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: navidrome
          image: deluan/navidrome@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2
          imagePullPolicy: IfNotPresent
          env:
            - name: ND_MUSICFOLDER
              value: "/media/music"
            - name: ND_SCANSCHEDULE
              value: "1h"
            - name: ND_LOGLEVEL
              value: "info"
            - name: ND_SCANNER_PURGEMISSING
              value: "always"
            - name: ND_BASEURL
              value: ""
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: config-storage
              mountPath: /data
            - name: media-storage
              mountPath: /media
              readOnly: true
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd
        - name: config-storage
          persistentVolumeClaim:
            claimName: navidrome-config
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: media
spec:
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4533
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - music.rupan.dev
      secretName: navidrome-tls
  rules:
    - host: music.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 80
