apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      initContainers:
        - name: install-plugin
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Downloading NaviSync plugin..."
              curl -L -o /plugins/navisync.ndp https://github.com/JEFF7712/NaviSync/releases/download/v0.1.11/navisync.ndp
          volumeMounts:
            - name: plugins-data
              mountPath: /plugins
      containers:
        - name: navidrome
          image: deluan/navidrome:latest
          imagePullPolicy: Always
          env:
            - name: ND_SCANSCHEDULE
              value: "1h"
            - name: ND_LOGLEVEL
              value: "info"
            - name: ND_BASEURL
              value: ""
            - name: ND_PLUGINS_ENABLED
              value: "true"
            - name: ND_PLUGINS_FOLDER
              value: "/data/plugins"
            - name: ND_PLUGINS_AUTORELOAD
              value: "true"
            - name: ND_PLUGINS_LOGLEVEL
              value: "debug"
          ports:
            - containerPort: 4533
          volumeMounts:
            - name: config-storage
              mountPath: /data
            - name: media-storage
              mountPath: /music
              subPath: music
              readOnly: true
            - name: plugins-data
              mountPath: /data/plugins
      volumes:
        - name: plugins-data
          emptyDir: {}
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
        - name: config-storage
          persistentVolumeClaim:
            claimName: navidrome-config
---
apiVersion: v1
kind: Service
metadata:
  name: navidrome
  namespace: media
spec:
  selector:
    app: navidrome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4533
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navidrome
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - music.rupan.dev
      secretName: navidrome-tls
  rules:
    - host: music.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navidrome
                port:
                  number: 80