apiVersion: apps/v1
kind: Deployment
metadata:
  name: navispot
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navispot
  template:
    metadata:
      labels:
        app: navispot
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: navispot
          image: jeff7712/navispot:latest
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_APP_URL
              value: "https://navispot.rupan.dev"
            - name: SPOTIFY_REDIRECT_URI
              value: "https://navispot.rupan.dev/api/auth/callback"
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: navispot-secret
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: navispot-secret
                  key: SPOTIFY_CLIENT_SECRET
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: navispot
  namespace: media
spec:
  selector:
    app: navispot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: navispot
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - navispot.rupan.dev
      secretName: navispot-tls
  rules:
    - host: navispot.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: navispot
                port:
                  number: 80
