apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - qbittorrent
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: slskd
          image: slskd/slskd:latest
          ports:
            - containerPort: 5030
            - containerPort: 50300
          env:
            - name: SLSKD_REMOTE_CONFIGURATION
              value: "true"
          volumeMounts:
            - name: media-storage
              mountPath: /app/downloads
              subPath: downloads
            - name: media-storage
              mountPath: /app/slskd.yml
              subPath: config/slskd/slskd.yml
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media
spec:
  selector:
    app: slskd
  ports:
    - name: http
      port: 80
      targetPort: 5030
    - name: p2p
      port: 50300
      targetPort: 50300
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slskd
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - slskd.rupan.dev
      secretName: slskd-tls
  rules:
    - host: slskd.rupan.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slskd
                port:
                  number: 80