# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sonarr-config
#   namespace: media
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2Gi
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sonarr
#   namespace: media
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sonarr
#   template:
#     metadata:
#       labels:
#         app: sonarr
#       annotations:
#         reloader.stakater.com/auto: "true"
#     spec:
#       initContainers:
#         - name: fix-permissions
#           image: busybox
#           command: ["sh", "-c", "chown -R 1000:1000 /tv /downloads /config"]
#           volumeMounts:
#             - name: config-storage
#               mountPath: /config
#             - name: media-storage
#               mountPath: /downloads
#               subPath: downloads
#             - name: media-storage
#               mountPath: /tv
#               subPath: tv
#       containers:
#         - name: sonarr
#           image: lscr.io/linuxserver/sonarr:latest
#           env:
#             - name: PUID
#               value: "1000"
#             - name: PGID
#               value: "1000"
#             - name: TZ
#               value: "America/Chicago"
#           ports:
#             - containerPort: 8989
#           livenessProbe:
#             httpGet:
#               path: /ping
#               port: 8989
#             initialDelaySeconds: 120
#             periodSeconds: 20
#           volumeMounts:
#             - name: config-storage
#               mountPath: /config
#             - name: media-storage
#               mountPath: /downloads
#               subPath: downloads
#             - name: media-storage
#               mountPath: /tv
#               subPath: tv
#       volumes:
#         - name: media-storage
#           persistentVolumeClaim:
#             claimName: media-pvc-hdd
#         - name: config-storage
#           persistentVolumeClaim:
#             claimName: sonarr-config
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: sonarr
#   namespace: media
# spec:
#   selector:
#     app: sonarr
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8989

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: sonarr
#   namespace: media
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     traefik.ingress.kubernetes.io/router.entrypoints: websecure
# spec:
#   ingressClassName: traefik
#   tls:
#     - hosts:
#         - sonarr.rupan.dev
#       secretName: sonarr-tls
#   rules:
#     - host: sonarr.rupan.dev
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: sonarr
#                 port:
#                   number: 80