apiVersion: apps/v1
kind: Deployment
metadata:
  name: subgen
  namespace: media
  labels:
    app: subgen
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: subgen
  template:
    metadata:
      labels:
        app: subgen
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: subgen
          volumeMounts:
            - name: media-storage
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          image: mccloud/subgen@sha256:46b9a1f4e5d6ceedf2d309c784284a5b6ede72b1ebc8c1fffbb325979e15a30e
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
          resources:
            limits:
              memory: 4Gi
              cpu: "3"
            requests:
              memory: 2Gi
              cpu: "1"
          env:
            - name: WHISPER_MODEL
              value: "small"
            - name: TRANSCRIBE_DEVICE
              value: "cpu"
            - name: WHISPER_THREADS
              value: "4"
            - name: GUNICORN_WORKERS
              value: "1"
            - name: GUNICORN_TIMEOUT
              value: "3600"
            - name: CONCURRENT_TRANSCRIPTIONS
              value: "1"
          ports:
            - containerPort: 9000
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc-hdd
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: subgen
  namespace: media
spec:
  selector:
    app: subgen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
