{
 "title": "Server",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"host.docker.internal:9100\"} - node_memory_MemAvailable_bytes{instance=\"host.docker.internal:9100\"}) / node_memory_MemTotal_bytes{instance=\"host.docker.internal:9100\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"host.docker.internal:9100\"} - node_memory_SwapFree_bytes{instance=\"host.docker.internal:9100\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per-Core CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(cpu) (rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "# of Processes" }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"}[5m])",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} * 100)",
     "legendFormat": "Root Partition"
    }
   ]
  },
  {
   "title": "Download & Upload Speeds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{device!~\"lo|docker.*\"}[30s])) * 8) / 1000000",
     "legendFormat": "Download"
    },
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{device!~\"lo|docker.*\"}[30s])) * 8) / 1000000\n",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}