apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: distrojeff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distrojeff-web
  template:
    metadata:
      labels:
        app: distrojeff-web
    spec:
      containers:
      - name: web
        image: jeff7712/distrojeff-site:86ad37464306410802696e42261168d55242093b
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 101