apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-airvpn-external-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: slskd-airvpn-secret
    creationPolicy: Owner
  data:
    - secretKey: VPN_PORT_FORWARDING
      remoteRef:
        key: SLSKD_VPN_PORT_FORWARDING
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: SLSKD_WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: SLSKD_WIREGUARD_ADDRESSES
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: SLSKD_WIREGUARD_PRESHARED_KEY