apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airvpn-external-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-secret-store
    kind: ClusterSecretStore
  target:
    name: airvpn-secret
    creationPolicy: Owner
  data:
    - secretKey: VPN_PORT_FORWARDING
      remoteRef:
        key: AIRVPN_PORT_FORWARDING
        
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: AIRVPN_PRIVATE_KEY
        
    - secretKey: WIREGUARD_PRESHARED_KEY
      remoteRef:
        key: AIRVPN_PRESHARED_KEY
        
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: AIRVPN_ADDRESSES