apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apptly-app-secrets-eso
  namespace: apptly
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: apptly-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "postgresql://apptly:{{ .db_password }}@postgres:5432/apptly"
        BETA_ADMIN_TOKEN: "{{ .beta_admin_token }}"
        SLACK_BETA_WEBHOOK_URL: "{{ .slack_beta_webhook_url }}"
        POSTGRES_HOST: "postgres"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "apptly"
        POSTGRES_USER: "apptly"
        POSTGRES_PASSWORD: "{{ .db_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: APPTLY_DB_PASSWORD
    - secretKey: beta_admin_token
      remoteRef:
        key: APPTLY_BETA_ADMIN_TOKEN
    - secretKey: slack_beta_webhook_url
      remoteRef:
        key: APPTLY_SLACK_BETA_WEBHOOK_URL
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apptly-postgres-secrets-eso
  namespace: apptly
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_DB: "apptly"
        POSTGRES_USER: "apptly"
        POSTGRES_PASSWORD: "{{ .db_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: APPTLY_DB_PASSWORD
