apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-eso
  namespace: cert-manager
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore

  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      type: Opaque

  data:
  - secretKey: api-token
    remoteRef:
      key: CF_API_TOKEN