apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-agent-token-eso
  namespace: gitlab-agent-homelab
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore

  target:
    name: gitlab-agent-token
    creationPolicy: Owner
    template:
      type: Opaque

  data:
  - secretKey: token
    remoteRef:
      key: GITLAB_AGENT_TOKEN