apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-backup-credentials-eso
  namespace: longhorn-system
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore

  target:
    name: r2-backup-credentials
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: R2_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: R2_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: R2_ENDPOINTS
