apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-eso
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: n8n-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        N8N_ENCRYPTION_KEY: "{{ .encryption_key }}"
  data:
  - secretKey: encryption_key
    remoteRef:
      key: N8N_ENCRYPTION_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-auth-eso
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: n8n-db-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        postgresql-password: "{{ .db_password }}"
  data:
  - secretKey: db_password
    remoteRef:
      key: N8N_DB_PASSWORD