apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: attic-server-token-eso
  namespace: nix-cache
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore

  target:
    name: attic-tokens
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64: "{{ .key }}"

  data:
  - secretKey: key
    remoteRef:
      key: ATTIC_SERVER_TOKEN_HS256_SECRET_BASE64
