apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-creds
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: minio-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        accesskey: "admin"
        secretkey: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: MINIO_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-creds
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: grafana-admin-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "admin"
        admin-password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: GRAFANA_PASSWORD
