apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-creds-eso
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: postgres-creds
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        postgres-password: "{{ .postgres_admin }}"
        password: "{{ .n8n_user_pass }}"
  data:
  - secretKey: postgres_admin
    remoteRef:
      key: POSTGRES_SUPERUSER_PASSWORD
  - secretKey: n8n_user_pass
    remoteRef:
      key: N8N_DB_PASSWORD