apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets-eso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  data:
  - secretKey: RENOVATE_TOKEN
    remoteRef:
      key: RENOVATE_TOKEN

  - secretKey: GITHUB_COM_TOKEN
    remoteRef:
      key: GITHUB_TOKEN