apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-secrets-eso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: renovate-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: gitlab-token
      remoteRef:
        key: RENOVATE_TOKEN

    - secretKey: github-token
      remoteRef:
        key: GITHUB_TOKEN