apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slskd-seed-secret-eso
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: slskd-seed-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        slskd.yml: |
          directories:
            incomplete: /data/downloads/soulseek/incomplete
            downloads: /data/downloads/soulseek
          shares:
            directories:
              - /data/music
            filters:
              - \.ini$
              - Thumbs.db$
              - \.DS_Store$
          web:
            authentication:
              api_keys:
                my_api_key:
                  key: "{{ .slskd_api_key }}"
                  role: administrator
                  cidr: 0.0.0.0/0,::/0
          soulseek:
            address: vps.slsknet.org
            port: 2271
            username: "{{ .slskd_username }}"
            password: "{{ .slskd_password }}"
            description: |
              A slskd user. https://github.com/slskd/slskd
            listen_ip_address: 0.0.0.0
            listen_port: 50300
  data:
    - secretKey: slskd_api_key
      remoteRef:
        key: SLSKD_API_KEY
    - secretKey: slskd_username
      remoteRef:
        key: SLSKD_USERNAME
    - secretKey: slskd_password
      remoteRef:
        key: SLSKD_PASSWORD
