apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spotify-clone-secret-eso
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gitlab-backend
    kind: ClusterSecretStore
  target:
    name: spotify-clone-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: SPOTIFY_CLONE_POSTGRES_PASSWORD
    - secretKey: LIDARR_API_KEY
      remoteRef:
        key: SPOTIFY_CLONE_LIDARR_API_KEY
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: SPOTIFY_CLONE_SPOTIFY_CLIENT_ID
    - secretKey: SESSION_SECRET
      remoteRef:
        key: SPOTIFY_CLONE_SESSION_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: SPOTIFY_CLONE_ENCRYPTION_KEY
